-- Baseline schema: reproduces the tables previously generated by Hibernate
-- ddl-auto=update, so `ddl-auto=validate` passes on a fresh database.
-- On pre-existing databases this migration is skipped (baseline-on-migrate).

CREATE TABLE IF NOT EXISTS roles (
    role_name        VARCHAR(255) NOT NULL,
    role_description VARCHAR(255),
    PRIMARY KEY (role_name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
    user_id      BIGINT       NOT NULL AUTO_INCREMENT,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    username     VARCHAR(255),
    password     VARCHAR(255),
    phone_number VARCHAR(255),
    is_active    BIT          NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE KEY uk_users_username (username)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_role (
    user_id BIGINT       NOT NULL,
    role_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES roles (role_name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories (
    cat_id      BIGINT NOT NULL AUTO_INCREMENT,
    title       VARCHAR(255),
    description VARCHAR(255),
    PRIMARY KEY (cat_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS quizzes (
    quiz_id          BIGINT        NOT NULL AUTO_INCREMENT,
    title            VARCHAR(255),
    description      VARCHAR(5000),
    is_active        BIT           NOT NULL,
    num_of_questions INT           NOT NULL,
    category_cat_id  BIGINT,
    PRIMARY KEY (quiz_id),
    CONSTRAINT fk_quizzes_category FOREIGN KEY (category_cat_id) REFERENCES categories (cat_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS questions (
    ques_id      BIGINT        NOT NULL AUTO_INCREMENT,
    question     VARCHAR(5000),
    image        VARCHAR(255),
    option1      VARCHAR(255),
    option2      VARCHAR(255),
    option3      VARCHAR(255),
    option4      VARCHAR(255),
    answer       VARCHAR(255),
    quiz_quiz_id BIGINT,
    PRIMARY KEY (ques_id),
    CONSTRAINT fk_questions_quiz FOREIGN KEY (quiz_quiz_id) REFERENCES quizzes (quiz_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS quiz_results (
    quiz_res_id          BIGINT NOT NULL AUTO_INCREMENT,
    user_id              BIGINT,
    total_obtained_marks FLOAT  NOT NULL,
    attempt_datetime     VARCHAR(255),
    quiz_quiz_id         BIGINT,
    PRIMARY KEY (quiz_res_id),
    CONSTRAINT fk_quiz_results_quiz FOREIGN KEY (quiz_quiz_id) REFERENCES quizzes (quiz_id)
) ENGINE=InnoDB;
